### ISSUE TITLE
text is always blank

### ISSUE THREAD

**Issue by possiphil** [MuhammadSaudKhan/LanguageTranslator#1]
Hello,
I have started using the translate API (as described in your post on medium) and it worked.
However now, even thou I haven't changed anything, just added more Textviews (mainly translating Textviews and Buttons) and it stopped working (the String "text" is always blank, even thou I get the language code and the string of the textview). Is there maybe a limit to how many times this api can be called or at a number of different locations? Do you have any solution for me?

**Comment by possiphil** [comment]
The first time the app is installed, it works and after that my textviews are just blank.

**Comment by MuhammadSaudKhan** [comment]
Yes there is limit. If too many request is sent. API will block ip till 30 minutes.

**Comment by possiphil** [comment]
May you have any alternative for this that does not have a limit?
